version: "3.9"

services:
  backend:
    restart: unless-stopped
    build:
      context: .
    image: placement_stats
    command: sh -c /app/entrypoint.prod
    container_name: placement_stats
    volumes:
        - "./db.sqlite3:/app/db.sqlite3"
    ports:
      - "8011:8000"
    env_file:
      - .env.prod