version: "3.9"

services:
  backend:
    restart: unless-stopped
    build:
      context: .
    image: placement_stats
    container_name: placement_stats
    volumes:
        - "./db.sqlite3:/app/db.sqlite3"
    ports:
      - "8010:8000"
    env_file:
      - .env.prod